name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change this if deploying from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ProShop_Environment  # Reference the GitHub Environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies (Backend)
        run: npm install

      - name: Install Dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Set Environment Variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> $GITHUB_ENV
          echo "PAGINATION_LIMIT=${{ secrets.PAGINATION_LIMIT }}" >> $GITHUB_ENV
          echo "PAYPAL_APP_SECRET=${{ secrets.PAYPAL_APP_SECRET }}" >> $GITHUB_ENV
          echo "PAYPAL_API_URL=${{ secrets.PAYPAL_API_URL }}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ProShop"  # Change to your Azure App Service name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .